name: EC2 자동 배포하기

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 가져오기
        uses: actions/checkout@v5

      - name: Node.js 설치하기
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: 의존성(라이브러리) 설치
        run: npm ci

      - name: .env 파일 생성
        run: echo "${{ secrets.ENV }}" > .env

      - name: 빌드
        run: npm run build

      - name: 배포에 필요한 파일들만 압축
        run: tar -czvf nextjs-aws-test.tar.gz .next .env package.json package-lock.json

      - name: EC2로 압축된 파일을 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          source: nextjs-aws-test.tar.gz
          target: /home/ubuntu/nextjs-aws-test/build

      - name: SSH로 EC2 접속 후에 실행
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          script: |
            set -e
            rm -rf /home/ubuntu/nextjs-aws-test/current
            mkdir /home/ubuntu/nextjs-aws-test/current
            mv /home/ubuntu/nextjs-aws-test/build/nextjs-aws-test.tar.gz /home/ubuntu/nextjs-aws-test/current/nextjs-aws-test.tar.gz
            cd /home/ubuntu/nextjs-aws-test/current
            tar -xvf nextjs-aws-test.tar.gz
            npm install
            pm2 kill
            pm2 start npm --name "nextjs-app" -- start
