name: EC2 자동 배포하기

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH로 EC2에 원격으로 접속한 후 배포한다.
        uses: appleboy/ssh-action@v1
        env:
          # ENV라는 변수에 github secrets에 저장된 ENV 값을 넣어준다.
          ENV: ${{ secrets.ENV }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PEM_KEY }}
          envs: ENV
          script: |
            set -e
            cd /home/ubuntu/fesi12-aws
            rm -rf .env 
            git pull origin main
            echo "$ENV" > .env
            pm2 kill
            npm ci
            npm run build
            pm2 start npm --name "nextjs-app" -- start
